// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 15001_S2CGetPlayerProfileRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "15001_S2CGetPlayerProfileRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CGetPlayerProfileRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CGetPlayerProfileRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_15001_5fS2CGetPlayerProfileRsp_2eproto() {
  protobuf_AddDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "15001_S2CGetPlayerProfileRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CGetPlayerProfileRsp_descriptor_ = file->message_type(0);
  static const int S2CGetPlayerProfileRsp_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetPlayerProfileRsp, nickname_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetPlayerProfileRsp, last_login_),
  };
  S2CGetPlayerProfileRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CGetPlayerProfileRsp_descriptor_,
      S2CGetPlayerProfileRsp::default_instance_,
      S2CGetPlayerProfileRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetPlayerProfileRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CGetPlayerProfileRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CGetPlayerProfileRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_15001_5fS2CGetPlayerProfileRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CGetPlayerProfileRsp_descriptor_, &S2CGetPlayerProfileRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_15001_5fS2CGetPlayerProfileRsp_2eproto() {
  delete S2CGetPlayerProfileRsp::default_instance_;
  delete S2CGetPlayerProfileRsp_reflection_;
}

void protobuf_AddDesc_15001_5fS2CGetPlayerProfileRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\"15001_S2CGetPlayerProfileRsp.proto\022\010Pr"
    "otocol\">\n\026S2CGetPlayerProfileRsp\022\020\n\010nick"
    "name\030\001 \002(\014\022\022\n\nlast_login\030\002 \002(\005", 110);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "15001_S2CGetPlayerProfileRsp.proto", &protobuf_RegisterTypes);
  S2CGetPlayerProfileRsp::default_instance_ = new S2CGetPlayerProfileRsp();
  S2CGetPlayerProfileRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_15001_5fS2CGetPlayerProfileRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_15001_5fS2CGetPlayerProfileRsp_2eproto {
  StaticDescriptorInitializer_15001_5fS2CGetPlayerProfileRsp_2eproto() {
    protobuf_AddDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
  }
} static_descriptor_initializer_15001_5fS2CGetPlayerProfileRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CGetPlayerProfileRsp::kNicknameFieldNumber;
const int S2CGetPlayerProfileRsp::kLastLoginFieldNumber;
#endif  // !_MSC_VER

S2CGetPlayerProfileRsp::S2CGetPlayerProfileRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CGetPlayerProfileRsp::InitAsDefaultInstance() {
}

S2CGetPlayerProfileRsp::S2CGetPlayerProfileRsp(const S2CGetPlayerProfileRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CGetPlayerProfileRsp::SharedCtor() {
  _cached_size_ = 0;
  nickname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  last_login_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CGetPlayerProfileRsp::~S2CGetPlayerProfileRsp() {
  SharedDtor();
}

void S2CGetPlayerProfileRsp::SharedDtor() {
  if (nickname_ != &::google::protobuf::internal::kEmptyString) {
    delete nickname_;
  }
  if (this != default_instance_) {
  }
}

void S2CGetPlayerProfileRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CGetPlayerProfileRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CGetPlayerProfileRsp_descriptor_;
}

const S2CGetPlayerProfileRsp& S2CGetPlayerProfileRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_15001_5fS2CGetPlayerProfileRsp_2eproto();
  return *default_instance_;
}

S2CGetPlayerProfileRsp* S2CGetPlayerProfileRsp::default_instance_ = NULL;

S2CGetPlayerProfileRsp* S2CGetPlayerProfileRsp::New() const {
  return new S2CGetPlayerProfileRsp;
}

void S2CGetPlayerProfileRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_nickname()) {
      if (nickname_ != &::google::protobuf::internal::kEmptyString) {
        nickname_->clear();
      }
    }
    last_login_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CGetPlayerProfileRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required bytes nickname = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_nickname()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_last_login;
        break;
      }

      // required int32 last_login = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_last_login:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &last_login_)));
          set_has_last_login();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CGetPlayerProfileRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required bytes nickname = 1;
  if (has_nickname()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytes(
      1, this->nickname(), output);
  }

  // required int32 last_login = 2;
  if (has_last_login()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->last_login(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CGetPlayerProfileRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required bytes nickname = 1;
  if (has_nickname()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->nickname(), target);
  }

  // required int32 last_login = 2;
  if (has_last_login()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->last_login(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CGetPlayerProfileRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required bytes nickname = 1;
    if (has_nickname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->nickname());
    }

    // required int32 last_login = 2;
    if (has_last_login()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->last_login());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CGetPlayerProfileRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CGetPlayerProfileRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CGetPlayerProfileRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CGetPlayerProfileRsp::MergeFrom(const S2CGetPlayerProfileRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_nickname()) {
      set_nickname(from.nickname());
    }
    if (from.has_last_login()) {
      set_last_login(from.last_login());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CGetPlayerProfileRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CGetPlayerProfileRsp::CopyFrom(const S2CGetPlayerProfileRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CGetPlayerProfileRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void S2CGetPlayerProfileRsp::Swap(S2CGetPlayerProfileRsp* other) {
  if (other != this) {
    std::swap(nickname_, other->nickname_);
    std::swap(last_login_, other->last_login_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CGetPlayerProfileRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CGetPlayerProfileRsp_descriptor_;
  metadata.reflection = S2CGetPlayerProfileRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
