// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21006_S2CRoomCancleRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21006_S2CRoomCancleRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CRoomCancleRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CRoomCancleRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21006_5fS2CRoomCancleRsp_2eproto() {
  protobuf_AddDesc_21006_5fS2CRoomCancleRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21006_S2CRoomCancleRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CRoomCancleRsp_descriptor_ = file->message_type(0);
  static const int S2CRoomCancleRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCancleRsp, id_),
  };
  S2CRoomCancleRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CRoomCancleRsp_descriptor_,
      S2CRoomCancleRsp::default_instance_,
      S2CRoomCancleRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCancleRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CRoomCancleRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CRoomCancleRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21006_5fS2CRoomCancleRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CRoomCancleRsp_descriptor_, &S2CRoomCancleRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21006_5fS2CRoomCancleRsp_2eproto() {
  delete S2CRoomCancleRsp::default_instance_;
  delete S2CRoomCancleRsp_reflection_;
}

void protobuf_AddDesc_21006_5fS2CRoomCancleRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\03421006_S2CRoomCancleRsp.proto\022\010Protocol"
    "\"\036\n\020S2CRoomCancleRsp\022\n\n\002id\030\001 \002(\r", 72);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21006_S2CRoomCancleRsp.proto", &protobuf_RegisterTypes);
  S2CRoomCancleRsp::default_instance_ = new S2CRoomCancleRsp();
  S2CRoomCancleRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21006_5fS2CRoomCancleRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21006_5fS2CRoomCancleRsp_2eproto {
  StaticDescriptorInitializer_21006_5fS2CRoomCancleRsp_2eproto() {
    protobuf_AddDesc_21006_5fS2CRoomCancleRsp_2eproto();
  }
} static_descriptor_initializer_21006_5fS2CRoomCancleRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CRoomCancleRsp::kIdFieldNumber;
#endif  // !_MSC_VER

S2CRoomCancleRsp::S2CRoomCancleRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CRoomCancleRsp::InitAsDefaultInstance() {
}

S2CRoomCancleRsp::S2CRoomCancleRsp(const S2CRoomCancleRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CRoomCancleRsp::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CRoomCancleRsp::~S2CRoomCancleRsp() {
  SharedDtor();
}

void S2CRoomCancleRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void S2CRoomCancleRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CRoomCancleRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CRoomCancleRsp_descriptor_;
}

const S2CRoomCancleRsp& S2CRoomCancleRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21006_5fS2CRoomCancleRsp_2eproto();
  return *default_instance_;
}

S2CRoomCancleRsp* S2CRoomCancleRsp::default_instance_ = NULL;

S2CRoomCancleRsp* S2CRoomCancleRsp::New() const {
  return new S2CRoomCancleRsp;
}

void S2CRoomCancleRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CRoomCancleRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CRoomCancleRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CRoomCancleRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CRoomCancleRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CRoomCancleRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CRoomCancleRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CRoomCancleRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CRoomCancleRsp::MergeFrom(const S2CRoomCancleRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CRoomCancleRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CRoomCancleRsp::CopyFrom(const S2CRoomCancleRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CRoomCancleRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CRoomCancleRsp::Swap(S2CRoomCancleRsp* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CRoomCancleRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CRoomCancleRsp_descriptor_;
  metadata.reflection = S2CRoomCancleRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
