// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21008_S2CRoomInfoChangeRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21008_S2CRoomInfoChangeRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CSRoomInfoChangeRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CSRoomInfoChangeRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21008_5fS2CRoomInfoChangeRsp_2eproto() {
  protobuf_AddDesc_21008_5fS2CRoomInfoChangeRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21008_S2CRoomInfoChangeRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CSRoomInfoChangeRsp_descriptor_ = file->message_type(0);
  static const int S2CSRoomInfoChangeRsp_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeRsp, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeRsp, room_name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeRsp, player_count_),
  };
  S2CSRoomInfoChangeRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CSRoomInfoChangeRsp_descriptor_,
      S2CSRoomInfoChangeRsp::default_instance_,
      S2CSRoomInfoChangeRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CSRoomInfoChangeRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CSRoomInfoChangeRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21008_5fS2CRoomInfoChangeRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CSRoomInfoChangeRsp_descriptor_, &S2CSRoomInfoChangeRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21008_5fS2CRoomInfoChangeRsp_2eproto() {
  delete S2CSRoomInfoChangeRsp::default_instance_;
  delete S2CSRoomInfoChangeRsp_reflection_;
}

void protobuf_AddDesc_21008_5fS2CRoomInfoChangeRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n 21008_S2CRoomInfoChangeRsp.proto\022\010Prot"
    "ocol\"L\n\025S2CSRoomInfoChangeRsp\022\n\n\002id\030\001 \002("
    "\r\022\021\n\troom_name\030\002 \001(\t\022\024\n\014player_count\030\003 \001"
    "(\r", 122);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21008_S2CRoomInfoChangeRsp.proto", &protobuf_RegisterTypes);
  S2CSRoomInfoChangeRsp::default_instance_ = new S2CSRoomInfoChangeRsp();
  S2CSRoomInfoChangeRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21008_5fS2CRoomInfoChangeRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21008_5fS2CRoomInfoChangeRsp_2eproto {
  StaticDescriptorInitializer_21008_5fS2CRoomInfoChangeRsp_2eproto() {
    protobuf_AddDesc_21008_5fS2CRoomInfoChangeRsp_2eproto();
  }
} static_descriptor_initializer_21008_5fS2CRoomInfoChangeRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CSRoomInfoChangeRsp::kIdFieldNumber;
const int S2CSRoomInfoChangeRsp::kRoomNameFieldNumber;
const int S2CSRoomInfoChangeRsp::kPlayerCountFieldNumber;
#endif  // !_MSC_VER

S2CSRoomInfoChangeRsp::S2CSRoomInfoChangeRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CSRoomInfoChangeRsp::InitAsDefaultInstance() {
}

S2CSRoomInfoChangeRsp::S2CSRoomInfoChangeRsp(const S2CSRoomInfoChangeRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CSRoomInfoChangeRsp::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  player_count_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CSRoomInfoChangeRsp::~S2CSRoomInfoChangeRsp() {
  SharedDtor();
}

void S2CSRoomInfoChangeRsp::SharedDtor() {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    delete room_name_;
  }
  if (this != default_instance_) {
  }
}

void S2CSRoomInfoChangeRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CSRoomInfoChangeRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CSRoomInfoChangeRsp_descriptor_;
}

const S2CSRoomInfoChangeRsp& S2CSRoomInfoChangeRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21008_5fS2CRoomInfoChangeRsp_2eproto();
  return *default_instance_;
}

S2CSRoomInfoChangeRsp* S2CSRoomInfoChangeRsp::default_instance_ = NULL;

S2CSRoomInfoChangeRsp* S2CSRoomInfoChangeRsp::New() const {
  return new S2CSRoomInfoChangeRsp;
}

void S2CSRoomInfoChangeRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = 0u;
    if (has_room_name()) {
      if (room_name_ != &::google::protobuf::internal::kEmptyString) {
        room_name_->clear();
      }
    }
    player_count_ = 0u;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CSRoomInfoChangeRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_room_name;
        break;
      }

      // optional string room_name = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_room_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_room_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->room_name().data(), this->room_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_player_count;
        break;
      }

      // optional uint32 player_count = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_player_count:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &player_count_)));
          set_has_player_count();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CSRoomInfoChangeRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // optional string room_name = 2;
  if (has_room_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->room_name().data(), this->room_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->room_name(), output);
  }

  // optional uint32 player_count = 3;
  if (has_player_count()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->player_count(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CSRoomInfoChangeRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // optional string room_name = 2;
  if (has_room_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->room_name().data(), this->room_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->room_name(), target);
  }

  // optional uint32 player_count = 3;
  if (has_player_count()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->player_count(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CSRoomInfoChangeRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->id());
    }

    // optional string room_name = 2;
    if (has_room_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->room_name());
    }

    // optional uint32 player_count = 3;
    if (has_player_count()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->player_count());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CSRoomInfoChangeRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CSRoomInfoChangeRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CSRoomInfoChangeRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CSRoomInfoChangeRsp::MergeFrom(const S2CSRoomInfoChangeRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_room_name()) {
      set_room_name(from.room_name());
    }
    if (from.has_player_count()) {
      set_player_count(from.player_count());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CSRoomInfoChangeRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CSRoomInfoChangeRsp::CopyFrom(const S2CSRoomInfoChangeRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CSRoomInfoChangeRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CSRoomInfoChangeRsp::Swap(S2CSRoomInfoChangeRsp* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(room_name_, other->room_name_);
    std::swap(player_count_, other->player_count_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CSRoomInfoChangeRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CSRoomInfoChangeRsp_descriptor_;
  metadata.reflection = S2CSRoomInfoChangeRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
