// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21013_C2SKickPlayerReq.proto

#ifndef PROTOBUF_21013_5fC2SKickPlayerReq_2eproto__INCLUDED
#define PROTOBUF_21013_5fC2SKickPlayerReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_21013_5fC2SKickPlayerReq_2eproto();
void protobuf_AssignDesc_21013_5fC2SKickPlayerReq_2eproto();
void protobuf_ShutdownFile_21013_5fC2SKickPlayerReq_2eproto();

class C2SKickPlayerReq;

// ===================================================================

class C2SKickPlayerReq : public ::google::protobuf::Message {
 public:
  C2SKickPlayerReq();
  virtual ~C2SKickPlayerReq();

  C2SKickPlayerReq(const C2SKickPlayerReq& from);

  inline C2SKickPlayerReq& operator=(const C2SKickPlayerReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2SKickPlayerReq& default_instance();

  void Swap(C2SKickPlayerReq* other);

  // implements Message ----------------------------------------------

  C2SKickPlayerReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const C2SKickPlayerReq& from);
  void MergeFrom(const C2SKickPlayerReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required string kicked_palyer = 2;
  inline bool has_kicked_palyer() const;
  inline void clear_kicked_palyer();
  static const int kKickedPalyerFieldNumber = 2;
  inline const ::std::string& kicked_palyer() const;
  inline void set_kicked_palyer(const ::std::string& value);
  inline void set_kicked_palyer(const char* value);
  inline void set_kicked_palyer(const char* value, size_t size);
  inline ::std::string* mutable_kicked_palyer();
  inline ::std::string* release_kicked_palyer();
  inline void set_allocated_kicked_palyer(::std::string* kicked_palyer);

  // @@protoc_insertion_point(class_scope:Protocol.C2SKickPlayerReq)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_kicked_palyer();
  inline void clear_has_kicked_palyer();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* kicked_palyer_;
  ::google::protobuf::uint32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_21013_5fC2SKickPlayerReq_2eproto();
  friend void protobuf_AssignDesc_21013_5fC2SKickPlayerReq_2eproto();
  friend void protobuf_ShutdownFile_21013_5fC2SKickPlayerReq_2eproto();

  void InitAsDefaultInstance();
  static C2SKickPlayerReq* default_instance_;
};
// ===================================================================


// ===================================================================

// C2SKickPlayerReq

// required uint32 id = 1;
inline bool C2SKickPlayerReq::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void C2SKickPlayerReq::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void C2SKickPlayerReq::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void C2SKickPlayerReq::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 C2SKickPlayerReq::id() const {
  return id_;
}
inline void C2SKickPlayerReq::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string kicked_palyer = 2;
inline bool C2SKickPlayerReq::has_kicked_palyer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void C2SKickPlayerReq::set_has_kicked_palyer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void C2SKickPlayerReq::clear_has_kicked_palyer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void C2SKickPlayerReq::clear_kicked_palyer() {
  if (kicked_palyer_ != &::google::protobuf::internal::kEmptyString) {
    kicked_palyer_->clear();
  }
  clear_has_kicked_palyer();
}
inline const ::std::string& C2SKickPlayerReq::kicked_palyer() const {
  return *kicked_palyer_;
}
inline void C2SKickPlayerReq::set_kicked_palyer(const ::std::string& value) {
  set_has_kicked_palyer();
  if (kicked_palyer_ == &::google::protobuf::internal::kEmptyString) {
    kicked_palyer_ = new ::std::string;
  }
  kicked_palyer_->assign(value);
}
inline void C2SKickPlayerReq::set_kicked_palyer(const char* value) {
  set_has_kicked_palyer();
  if (kicked_palyer_ == &::google::protobuf::internal::kEmptyString) {
    kicked_palyer_ = new ::std::string;
  }
  kicked_palyer_->assign(value);
}
inline void C2SKickPlayerReq::set_kicked_palyer(const char* value, size_t size) {
  set_has_kicked_palyer();
  if (kicked_palyer_ == &::google::protobuf::internal::kEmptyString) {
    kicked_palyer_ = new ::std::string;
  }
  kicked_palyer_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* C2SKickPlayerReq::mutable_kicked_palyer() {
  set_has_kicked_palyer();
  if (kicked_palyer_ == &::google::protobuf::internal::kEmptyString) {
    kicked_palyer_ = new ::std::string;
  }
  return kicked_palyer_;
}
inline ::std::string* C2SKickPlayerReq::release_kicked_palyer() {
  clear_has_kicked_palyer();
  if (kicked_palyer_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = kicked_palyer_;
    kicked_palyer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void C2SKickPlayerReq::set_allocated_kicked_palyer(::std::string* kicked_palyer) {
  if (kicked_palyer_ != &::google::protobuf::internal::kEmptyString) {
    delete kicked_palyer_;
  }
  if (kicked_palyer) {
    set_has_kicked_palyer();
    kicked_palyer_ = kicked_palyer;
  } else {
    clear_has_kicked_palyer();
    kicked_palyer_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_21013_5fC2SKickPlayerReq_2eproto__INCLUDED
