// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21010_S2CPlayerEnterRoomReq.proto

#ifndef PROTOBUF_21010_5fS2CPlayerEnterRoomReq_2eproto__INCLUDED
#define PROTOBUF_21010_5fS2CPlayerEnterRoomReq_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_21010_5fS2CPlayerEnterRoomReq_2eproto();
void protobuf_AssignDesc_21010_5fS2CPlayerEnterRoomReq_2eproto();
void protobuf_ShutdownFile_21010_5fS2CPlayerEnterRoomReq_2eproto();

class S2CPlayerEnterRoomRsp;

// ===================================================================

class S2CPlayerEnterRoomRsp : public ::google::protobuf::Message {
 public:
  S2CPlayerEnterRoomRsp();
  virtual ~S2CPlayerEnterRoomRsp();

  S2CPlayerEnterRoomRsp(const S2CPlayerEnterRoomRsp& from);

  inline S2CPlayerEnterRoomRsp& operator=(const S2CPlayerEnterRoomRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CPlayerEnterRoomRsp& default_instance();

  void Swap(S2CPlayerEnterRoomRsp* other);

  // implements Message ----------------------------------------------

  S2CPlayerEnterRoomRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CPlayerEnterRoomRsp& from);
  void MergeFrom(const S2CPlayerEnterRoomRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string player_name = 1;
  inline bool has_player_name() const;
  inline void clear_player_name();
  static const int kPlayerNameFieldNumber = 1;
  inline const ::std::string& player_name() const;
  inline void set_player_name(const ::std::string& value);
  inline void set_player_name(const char* value);
  inline void set_player_name(const char* value, size_t size);
  inline ::std::string* mutable_player_name();
  inline ::std::string* release_player_name();
  inline void set_allocated_player_name(::std::string* player_name);

  // @@protoc_insertion_point(class_scope:Protocol.S2CPlayerEnterRoomRsp)
 private:
  inline void set_has_player_name();
  inline void clear_has_player_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* player_name_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_21010_5fS2CPlayerEnterRoomReq_2eproto();
  friend void protobuf_AssignDesc_21010_5fS2CPlayerEnterRoomReq_2eproto();
  friend void protobuf_ShutdownFile_21010_5fS2CPlayerEnterRoomReq_2eproto();

  void InitAsDefaultInstance();
  static S2CPlayerEnterRoomRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CPlayerEnterRoomRsp

// required string player_name = 1;
inline bool S2CPlayerEnterRoomRsp::has_player_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CPlayerEnterRoomRsp::set_has_player_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CPlayerEnterRoomRsp::clear_has_player_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CPlayerEnterRoomRsp::clear_player_name() {
  if (player_name_ != &::google::protobuf::internal::kEmptyString) {
    player_name_->clear();
  }
  clear_has_player_name();
}
inline const ::std::string& S2CPlayerEnterRoomRsp::player_name() const {
  return *player_name_;
}
inline void S2CPlayerEnterRoomRsp::set_player_name(const ::std::string& value) {
  set_has_player_name();
  if (player_name_ == &::google::protobuf::internal::kEmptyString) {
    player_name_ = new ::std::string;
  }
  player_name_->assign(value);
}
inline void S2CPlayerEnterRoomRsp::set_player_name(const char* value) {
  set_has_player_name();
  if (player_name_ == &::google::protobuf::internal::kEmptyString) {
    player_name_ = new ::std::string;
  }
  player_name_->assign(value);
}
inline void S2CPlayerEnterRoomRsp::set_player_name(const char* value, size_t size) {
  set_has_player_name();
  if (player_name_ == &::google::protobuf::internal::kEmptyString) {
    player_name_ = new ::std::string;
  }
  player_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CPlayerEnterRoomRsp::mutable_player_name() {
  set_has_player_name();
  if (player_name_ == &::google::protobuf::internal::kEmptyString) {
    player_name_ = new ::std::string;
  }
  return player_name_;
}
inline ::std::string* S2CPlayerEnterRoomRsp::release_player_name() {
  clear_has_player_name();
  if (player_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = player_name_;
    player_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CPlayerEnterRoomRsp::set_allocated_player_name(::std::string* player_name) {
  if (player_name_ != &::google::protobuf::internal::kEmptyString) {
    delete player_name_;
  }
  if (player_name) {
    set_has_player_name();
    player_name_ = player_name;
  } else {
    clear_has_player_name();
    player_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_21010_5fS2CPlayerEnterRoomReq_2eproto__INCLUDED
