// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21012_S2CPlayerLeaveRoomRsp.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "21012_S2CPlayerLeaveRoomRsp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

namespace {

const ::google::protobuf::Descriptor* S2CPlayerLeaveRoomRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  S2CPlayerLeaveRoomRsp_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_21012_5fS2CPlayerLeaveRoomRsp_2eproto() {
  protobuf_AddDesc_21012_5fS2CPlayerLeaveRoomRsp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "21012_S2CPlayerLeaveRoomRsp.proto");
  GOOGLE_CHECK(file != NULL);
  S2CPlayerLeaveRoomRsp_descriptor_ = file->message_type(0);
  static const int S2CPlayerLeaveRoomRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CPlayerLeaveRoomRsp, player_name_),
  };
  S2CPlayerLeaveRoomRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      S2CPlayerLeaveRoomRsp_descriptor_,
      S2CPlayerLeaveRoomRsp::default_instance_,
      S2CPlayerLeaveRoomRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CPlayerLeaveRoomRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(S2CPlayerLeaveRoomRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(S2CPlayerLeaveRoomRsp));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_21012_5fS2CPlayerLeaveRoomRsp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    S2CPlayerLeaveRoomRsp_descriptor_, &S2CPlayerLeaveRoomRsp::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_21012_5fS2CPlayerLeaveRoomRsp_2eproto() {
  delete S2CPlayerLeaveRoomRsp::default_instance_;
  delete S2CPlayerLeaveRoomRsp_reflection_;
}

void protobuf_AddDesc_21012_5fS2CPlayerLeaveRoomRsp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n!21012_S2CPlayerLeaveRoomRsp.proto\022\010Pro"
    "tocol\",\n\025S2CPlayerLeaveRoomRsp\022\023\n\013player"
    "_name\030\001 \002(\t", 91);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "21012_S2CPlayerLeaveRoomRsp.proto", &protobuf_RegisterTypes);
  S2CPlayerLeaveRoomRsp::default_instance_ = new S2CPlayerLeaveRoomRsp();
  S2CPlayerLeaveRoomRsp::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_21012_5fS2CPlayerLeaveRoomRsp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_21012_5fS2CPlayerLeaveRoomRsp_2eproto {
  StaticDescriptorInitializer_21012_5fS2CPlayerLeaveRoomRsp_2eproto() {
    protobuf_AddDesc_21012_5fS2CPlayerLeaveRoomRsp_2eproto();
  }
} static_descriptor_initializer_21012_5fS2CPlayerLeaveRoomRsp_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int S2CPlayerLeaveRoomRsp::kPlayerNameFieldNumber;
#endif  // !_MSC_VER

S2CPlayerLeaveRoomRsp::S2CPlayerLeaveRoomRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void S2CPlayerLeaveRoomRsp::InitAsDefaultInstance() {
}

S2CPlayerLeaveRoomRsp::S2CPlayerLeaveRoomRsp(const S2CPlayerLeaveRoomRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void S2CPlayerLeaveRoomRsp::SharedCtor() {
  _cached_size_ = 0;
  player_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

S2CPlayerLeaveRoomRsp::~S2CPlayerLeaveRoomRsp() {
  SharedDtor();
}

void S2CPlayerLeaveRoomRsp::SharedDtor() {
  if (player_name_ != &::google::protobuf::internal::kEmptyString) {
    delete player_name_;
  }
  if (this != default_instance_) {
  }
}

void S2CPlayerLeaveRoomRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* S2CPlayerLeaveRoomRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return S2CPlayerLeaveRoomRsp_descriptor_;
}

const S2CPlayerLeaveRoomRsp& S2CPlayerLeaveRoomRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_21012_5fS2CPlayerLeaveRoomRsp_2eproto();
  return *default_instance_;
}

S2CPlayerLeaveRoomRsp* S2CPlayerLeaveRoomRsp::default_instance_ = NULL;

S2CPlayerLeaveRoomRsp* S2CPlayerLeaveRoomRsp::New() const {
  return new S2CPlayerLeaveRoomRsp;
}

void S2CPlayerLeaveRoomRsp::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_player_name()) {
      if (player_name_ != &::google::protobuf::internal::kEmptyString) {
        player_name_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool S2CPlayerLeaveRoomRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string player_name = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_player_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->player_name().data(), this->player_name().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void S2CPlayerLeaveRoomRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required string player_name = 1;
  if (has_player_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->player_name().data(), this->player_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->player_name(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* S2CPlayerLeaveRoomRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required string player_name = 1;
  if (has_player_name()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->player_name().data(), this->player_name().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->player_name(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int S2CPlayerLeaveRoomRsp::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required string player_name = 1;
    if (has_player_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->player_name());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void S2CPlayerLeaveRoomRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const S2CPlayerLeaveRoomRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const S2CPlayerLeaveRoomRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void S2CPlayerLeaveRoomRsp::MergeFrom(const S2CPlayerLeaveRoomRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_player_name()) {
      set_player_name(from.player_name());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void S2CPlayerLeaveRoomRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S2CPlayerLeaveRoomRsp::CopyFrom(const S2CPlayerLeaveRoomRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S2CPlayerLeaveRoomRsp::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void S2CPlayerLeaveRoomRsp::Swap(S2CPlayerLeaveRoomRsp* other) {
  if (other != this) {
    std::swap(player_name_, other->player_name_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata S2CPlayerLeaveRoomRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = S2CPlayerLeaveRoomRsp_descriptor_;
  metadata.reflection = S2CPlayerLeaveRoomRsp_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)
