// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: 21015_S2CNewRoomAddRsp.proto

#ifndef PROTOBUF_21015_5fS2CNewRoomAddRsp_2eproto__INCLUDED
#define PROTOBUF_21015_5fS2CNewRoomAddRsp_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Protocol {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_21015_5fS2CNewRoomAddRsp_2eproto();
void protobuf_AssignDesc_21015_5fS2CNewRoomAddRsp_2eproto();
void protobuf_ShutdownFile_21015_5fS2CNewRoomAddRsp_2eproto();

class S2CNewRoomAddRsp;

// ===================================================================

class S2CNewRoomAddRsp : public ::google::protobuf::Message {
 public:
  S2CNewRoomAddRsp();
  virtual ~S2CNewRoomAddRsp();

  S2CNewRoomAddRsp(const S2CNewRoomAddRsp& from);

  inline S2CNewRoomAddRsp& operator=(const S2CNewRoomAddRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2CNewRoomAddRsp& default_instance();

  void Swap(S2CNewRoomAddRsp* other);

  // implements Message ----------------------------------------------

  S2CNewRoomAddRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2CNewRoomAddRsp& from);
  void MergeFrom(const S2CNewRoomAddRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required string room_name = 2;
  inline bool has_room_name() const;
  inline void clear_room_name();
  static const int kRoomNameFieldNumber = 2;
  inline const ::std::string& room_name() const;
  inline void set_room_name(const ::std::string& value);
  inline void set_room_name(const char* value);
  inline void set_room_name(const char* value, size_t size);
  inline ::std::string* mutable_room_name();
  inline ::std::string* release_room_name();
  inline void set_allocated_room_name(::std::string* room_name);

  // @@protoc_insertion_point(class_scope:Protocol.S2CNewRoomAddRsp)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_room_name();
  inline void clear_has_room_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* room_name_;
  ::google::protobuf::uint32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_21015_5fS2CNewRoomAddRsp_2eproto();
  friend void protobuf_AssignDesc_21015_5fS2CNewRoomAddRsp_2eproto();
  friend void protobuf_ShutdownFile_21015_5fS2CNewRoomAddRsp_2eproto();

  void InitAsDefaultInstance();
  static S2CNewRoomAddRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// S2CNewRoomAddRsp

// required uint32 id = 1;
inline bool S2CNewRoomAddRsp::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2CNewRoomAddRsp::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2CNewRoomAddRsp::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2CNewRoomAddRsp::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 S2CNewRoomAddRsp::id() const {
  return id_;
}
inline void S2CNewRoomAddRsp::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required string room_name = 2;
inline bool S2CNewRoomAddRsp::has_room_name() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2CNewRoomAddRsp::set_has_room_name() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2CNewRoomAddRsp::clear_has_room_name() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2CNewRoomAddRsp::clear_room_name() {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    room_name_->clear();
  }
  clear_has_room_name();
}
inline const ::std::string& S2CNewRoomAddRsp::room_name() const {
  return *room_name_;
}
inline void S2CNewRoomAddRsp::set_room_name(const ::std::string& value) {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  room_name_->assign(value);
}
inline void S2CNewRoomAddRsp::set_room_name(const char* value) {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  room_name_->assign(value);
}
inline void S2CNewRoomAddRsp::set_room_name(const char* value, size_t size) {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  room_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2CNewRoomAddRsp::mutable_room_name() {
  set_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    room_name_ = new ::std::string;
  }
  return room_name_;
}
inline ::std::string* S2CNewRoomAddRsp::release_room_name() {
  clear_has_room_name();
  if (room_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = room_name_;
    room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2CNewRoomAddRsp::set_allocated_room_name(::std::string* room_name) {
  if (room_name_ != &::google::protobuf::internal::kEmptyString) {
    delete room_name_;
  }
  if (room_name) {
    set_has_room_name();
    room_name_ = room_name;
  } else {
    clear_has_room_name();
    room_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_21015_5fS2CNewRoomAddRsp_2eproto__INCLUDED
