// Generated by Zeus, DO NOT EDIT! 
// DateTime : 2013-11-04 ÷‹“ª 14:02:48  

#ifndef __PROTOBUF_H__ 
#define __PROTOBUF_H__ 

#include "protocol/10000_C2SLoginReq.pb.h" 
#include "protocol/10001_S2CLoginRsp.pb.h" 
#include "protocol/10002_C2SRegisterReq.pb.h" 
#include "protocol/10003_S2CRegisterRsp.pb.h" 
#include "protocol/15000_C2SGetPlayerProfileReq.pb.h" 
#include "protocol/15001_S2CGetPlayerProfileRsp.pb.h" 
#include "protocol/20000_C2SChatMessageReq.pb.h" 
#include "protocol/20001_S2CChatMessageNotify.pb.h" 
#include "protocol/99990_S2CError.pb.h" 
#include "protocol/99991_S2CErrorEx.pb.h" 

#endif 
