// Generated by Zeus, DO NOT EDIT! 
// DateTime : 2013-10-28 ÷‹“ª 12:47:13  

#ifndef __PROTOBUF_H__ 
#define __PROTOBUF_H__ 

#include "protocol/10000_C2SLoginReq.pb.h" 
#include "protocol/10001_S2CLoginRsp.pb.h" 
#include "protocol/10002_C2SRegisterReq.pb.h" 
#include "protocol/10003_S2CRegisterRsp.pb.h" 
#include "protocol/15000_C2SGetPlayerProfileReq.pb.h" 
#include "protocol/99990_S2CError.pb.h" 
#include "protocol/99991_S2CErrorEx.pb.h" 

#endif 
