//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 15001_S2CGetPlayerProfileRsp.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CGetPlayerProfileRsp")]
  public partial class S2CGetPlayerProfileRsp : global::ProtoBuf.IExtensible
  {
    public S2CGetPlayerProfileRsp() {}
    
    private ulong _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _gender;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private byte[] _nickname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private long _last_login;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"last_login", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_login
    {
      get { return _last_login; }
      set { _last_login = value; }
    }
    private ulong _guild_id;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"guild_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong guild_id
    {
      get { return _guild_id; }
      set { _guild_id = value; }
    }
    private byte[] _guild_name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"guild_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] guild_name
    {
      get { return _guild_name; }
      set { _guild_name = value; }
    }
    private uint _gold;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}