//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 21002_S2CRoomCreateRsp.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CRoomCreateRsp")]
  public partial class S2CRoomCreateRsp : global::ProtoBuf.IExtensible
  {
    public S2CRoomCreateRsp() {}
    
    private bool _room_create_result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_create_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool room_create_result
    {
      get { return _room_create_result; }
      set { _room_create_result = value; }
    }

    private uint _room_id = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }

    private byte[] _failed_reason = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"failed_reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] failed_reason
    {
      get { return _failed_reason; }
      set { _failed_reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}