//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 21004_S2CGetRoomListRsp.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CGetRoomListRsp")]
  public partial class S2CGetRoomListRsp : global::ProtoBuf.IExtensible
  {
    public S2CGetRoomListRsp() {}
    
    private readonly global::System.Collections.Generic.List<Protocol.S2CGetRoomListRsp.RoomInfo> _room_list = new global::System.Collections.Generic.List<Protocol.S2CGetRoomListRsp.RoomInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"room_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Protocol.S2CGetRoomListRsp.RoomInfo> room_list
    {
      get { return _room_list; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private string _room_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string room_name
    {
      get { return _room_name; }
      set { _room_name = value; }
    }
    private uint _player_count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"player_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint player_count
    {
      get { return _player_count; }
      set { _player_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}