//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 21013_C2SKickPlayerReq.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SKickPlayerReq")]
  public partial class C2SKickPlayerReq : global::ProtoBuf.IExtensible
  {
    public C2SKickPlayerReq() {}
    
    private uint _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private ulong _kicked_palyer_guid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"kicked_palyer_guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong kicked_palyer_guid
    {
      get { return _kicked_palyer_guid; }
      set { _kicked_palyer_guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}