//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 21010_S2CPlayerEnterRoomReq.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CPlayerEnterRoomRsp")]
  public partial class S2CPlayerEnterRoomRsp : global::ProtoBuf.IExtensible
  {
    public S2CPlayerEnterRoomRsp() {}
    
    private string _player_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string player_name
    {
      get { return _player_name; }
      set { _player_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}