//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 21013_C2SKickPlayerReq.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2SKickPlayerReq")]
  public partial class C2SKickPlayerReq : global::ProtoBuf.IExtensible
  {
    public C2SKickPlayerReq() {}
    
    private uint _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _kicked_palyer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"kicked_palyer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string kicked_palyer
    {
      get { return _kicked_palyer; }
      set { _kicked_palyer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}