//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 22001_C2STransferAccountsReq.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2STransferAccountsReq")]
  public partial class C2STransferAccountsReq : global::ProtoBuf.IExtensible
  {
    public C2STransferAccountsReq() {}
    
    private int _money_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"money_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money_type
    {
      get { return _money_type; }
      set { _money_type = value; }
    }
    private int _money_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money_count
    {
      get { return _money_count; }
      set { _money_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}