//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 99990_S2CError.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CError")]
  public partial class S2CError : global::ProtoBuf.IExtensible
  {
    public S2CError() {}
    
    private uint _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}