//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: 10003_S2CRegisterRsp.proto
namespace Protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2CRegisterRsp")]
  public partial class S2CRegisterRsp : global::ProtoBuf.IExtensible
  {
    public S2CRegisterRsp() {}
    
    private bool _register_result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"register_result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool register_result
    {
      get { return _register_result; }
      set { _register_result = value; }
    }

    private byte[] _failed_reason = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"failed_reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] failed_reason
    {
      get { return _failed_reason; }
      set { _failed_reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}